documentation:
  - changed-files:
      - any-glob-to-any-file:
          - readme.md
          - CONTRIBUTING.md
          - CODE_OF_CONDUCT.md
          - SECURITY.md

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/*
          - scripts/*
