allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  sqlite3: true
  vue-demi: true

packages:
  - 'apps/*'
  - 'packages/*'

overrides:
  nanoid: 6.0.1
  brace-expansion: 5.0.9
  fast-uri: 4.1.2
  undici: 8.10.0
  js-yaml: 5.3.0
