name: Bug Report
description: If an error or error occurs, report it here.
title: '[BUG]: '
labels: 'bug'
type: bug
body:
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: croffle_version
    attributes:
      label: Croffle version
      description: Include the exact Croffle version if you can. You can find it in bottom right sidebar.
      placeholder: v0.14.2
    validations:
      required: false

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe the bug in your own words. Include a short summary, reproduction steps, and anything else that seems relevant.
      placeholder: |
        Short summary:
        Croffle crashes when ...

        What happened?

        How can we reproduce it?
        1. ...
        2. ...
        3. ...

        Anything else that might help:
    validations:
      required: true
