name: Features Template
description: Template for feature requests
title: '[FEATURES]: '
labels: enhancement
type: feature
body:
  - type: textarea
    id: problem
    attributes:
      label: 'Problem or use case'
      description: 'What are you trying to do? Include a short summary and any other details that seem relevant.'
      placeholder: 'It is useful when ...'
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 'Proposal'
      description: 'Describe the feature you want to propose.'
      placeholder: 'It is useful when ...'
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: 'Alternative'
      description: 'Alternative or additional information that seems relevant. If you have no alternative, leave it blank.'
      placeholder: 'anything that seems relevant to help us understand the problem or use case.'
    validations:
      required: false
