name: 질문 사항 추가
description: 질문할 사항이 있을 때 질문을 추가합니다
title: '[Other]: '
body:
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Share the context, request, or issue. Include a short summary here too.
    validations:
      required: true
